### ISSUE TITLE
AttributeError: 'function' object has no attribute 'wrapped' in Django 2.2

### ISSUE THREAD

**Issue by taylor-cedar** [graphql-python/graphene-django#828]
In Django 2.2 (works fine in 2.1) tests, connections are overridden/monkeypatched with properties that throw errors, specifically the `connection.cursor` method. 

https://github.com/django/django/blob/master/django/test/testcases.py#L210

DjangoDebugMiddleware also monkeypatches `connection.cursor`.

https://github.com/graphql-python/graphene-django/blob/master/graphene_django/debug/sql/tracking.py#L43

This causes tests to fail when Django attempts to undo the monkeypatch.
https://github.com/django/django/blob/master/django/test/testcases.py#L220

The following error occurs:
```
ERROR: tearDownClass (point_of_sale.tests.graphene.queries.e2e_test_cash_and_check_batch_query.CashAndCheckBatchQueryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/cedar/api/common/testing/test_cases/db_test_case.py", line 44, in tearDownClass
    super(TestCase, cls).tearDownClass()
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 244, in tearDownClass
    cls._remove_databases_failures()
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 240, in _remove_databases_failures
    setattr(connection, name, method.wrapped)
AttributeError: 'function' object has no attribute 'wrapped'

----------------------------------------------------------------------
```

This test is using the Django test client to test the /graphql endpoint. 
https://docs.djangoproject.com/en/3.0/topics/testing/tools/#overview-and-a-quick-example

**Comment by r-azh** [comment]
I have the same issue when testing `/graphql` endpoint.

**Comment by Saigesp** [comment]
Same when testing with multiple databases, works fine in 2.1

**Comment by VackarAfzal** [comment]
I'm have the same issue, any updates on this?

**Comment by sebslomski** [comment]
This is caused by the graphene-django debug middleware.
In order fix it, set the graphene middlewares to `[]`

**Comment by crazyscientist** [comment]
Hi there,

> In order fix it, set the graphene middlewares to []

@sebslomski How and where would one do that? I'm asking because I have the following situation:

I have not set any graphene middlewares and my Django project uses (among others):

```
Django                         2.2.17
graphene                       2.1.8
graphene-django                2.15.0
graphene-django-optimizer      0.8.0
graphql-core                   2.3.2
graphql-relay                  2.0.1
```

Locally, on Ubuntu 20.04 with a Python 3.8 venv I can reproduce the reported traceback.

However in our Gitlab CI (openSUSE Leap 15.2 image with Python 3.6 and identical package versions) I **do not get this error**!

I'm wondering whether there might be another possible cause for this issue :thinking:

**Comment by frankmeszaros** [comment]
Hey @crazyscientist , I have been running into this _exact_ issue for the past week and it was driving me crazy! I'm not sure if this will help you but this was what fixed it for me on a relatively standard graphene-django setup:

## The error

in your `settings.py` (or wherever the settings for your tests live), we initially had:
```
# ... other stuff

GRAPHENE = {}

# ... other stuff
```

When this is the case, I was seeing the following  😢 :
![image](https://user-images.githubusercontent.com/15343791/107255003-db350d80-6a05-11eb-9145-06434ca9b4af.png)


## The Fix

in your `settings.py` (or wherever the settings for your tests live), we revised this to:
```
# ... other stuff

GRAPHENE = {
  "MIDDLEWARE": [] 
}

```

When this minor change was added, I was no longer getting the error 😄 :  
![image](https://user-images.githubusercontent.com/15343791/107255315-2b13d480-6a06-11eb-9a3f-afd37d381e5a.png)

**Comment by crazyscientist** [comment]
@frankmeszaros Thank you for the detailed answer. That fixed the problem for me as well. :smiley:

**Comment by chrisspen** [comment]
@frankmeszaros Is that an acceptable solution? If the Graphene middleware is causing unittests to randomly fail by corrupting the database connection, removing the middleware is only hiding the problem, which is buggy middleware. Even worse, you're excluding the middleware from your tests, so now you have less test coverage of a component you might be using in production.

**Comment by ganesanarun** [comment]
I ran into same problem today when I used [`SimpleTestCase`](https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.SimpleTestCase) instead of [`TestCase`](https://docs.djangoproject.com/en/3.2/topics/testing/tools/#testcase), but overriding `tearDownClass` solved my problem though.

```
@classmethod
    def tearDownClass(cls):
        pass
```

Not sure, whether that will fix your problem.

**Comment by delton-ecometrica** [comment]
Has there been any update on this error

**Comment by mahdyhamad** [comment]
Same problem with Django == `3.2` and graphene-django == `2.15.0`
