### ISSUE TITLE
After migrating to 2.0 cannot use custom arguments and relay.Node interface together

### ISSUE THREAD

**Issue by igo** [graphql-python/graphene-django#333]
After migrating to 2.0 cannot use custom attributes and ```relay.Node``` interface together.
```python
from graphene_django import DjangoObjectType, DjangoConnectionField
class OrganizerProfilType(DjangoObjectType):
    companies = DjangoConnectionField(CompanyType, slug=graphene.String())
    def resolve_companies(self, info, slug=None):
        companies = self.labels.order_by('name').all()
        if slug:
            companies = companies.filter(slug=slug)
        return companies

class CompanyType(DjangoObjectType):
    class Meta:
        model = Company
        only_fields = ['name', 'url', 'description', 'slug']
        interfaces = (graphene.relay.Node, )
```
Schema is generated correctly:
```
companies(
slug: String
before: String
after: String
first: Int
last: Int
): CompanyTypeConnection
```
Calling queries with slug works well but calling with arguments before, after, first, last causes error "resolve_companies() got an unexpected keyword argument 'before'". This approach was working before in 1.x release. What should be done to make it work in 2.0? Documentation seems obsolete.

**Comment by japrogramer** [comment]
could you try it with **args than args.get(...)?

**Comment by igo** [comment]
Ok, that worked, thanks. Now does that mean that graphene 2 cannot be used in a way that it was meant to be used?

**Comment by spockNinja** [comment]
@igo 

https://github.com/graphql-python/graphene-django/issues/333#issuecomment-348677621

I'm not too sure what you mean by "cannot be used in a way that it was meant to be used." Do you mean that there is some documentation out of date, or that you can't accomplish what you need after the upgrade, or something else entirely?

By overriding the resolver for a `DjangoConnectionField`, you have inherited the before/after/first/last arguments so that your resolver does not necessarily have to return a Queryset. Since your resolver could be getting data from anywhere, and should likely be utilizing the backend's mechanism for limits/range, all of the connection parameters could be handled in your new resolver. I'm fairly certain that by returning a queryset, those are still taken care of for you. However, the `**args` method seems like a reasonable approach if you want to ignore the other parameters.

If filtering by slug is the primary use of your custom resolver, you might take a look at http://docs.graphene-python.org/projects/django/en/latest/filtering/

**Comment by dopeboy** [comment]
I think we've reached a resolution here. Closing it down.
