### ISSUE TITLE
Error after upgrading from version 2.5.0 to 2.15.0

### ISSUE THREAD

**Issue by overide** [graphql-python/graphene-django#1223]
I was using version `2.5.0` and tried to upgrade to the current stable version `2.15.0`, after the upgrade It started throwing error - `TypeError: override_fields() got an unexpected keyword argument 'convert_choices_to_enum'` for `SerializerMutation`

* **What is the current behavior?**
Getting error `TypeError: override_fields() got an unexpected keyword argument 'convert_choices_to_enum'`

* **What is the expected behavior?**
Should work without any issue

* **Please tell us about your environment:**
  - Version: 2.15.0
  - Graphene version - 2.1.8
  - Python version - 3.7.4
  - Platform: Ubuntu 20.04.2 LTS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

```
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/django/views/generic/base.py", line 62, in view
    self = cls(**initkwargs)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/graphene_django/views.py", line 104, in __init__
    schema = graphene_settings.SCHEMA
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
  File "/home/overide/.pyenv/versions/3.7.4/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/overide/PROJECTS/work/spectra-backend/spectra/schema.py", line 4, in <module>
    from apps.user.mutation import UserProfileMutation
  File "/home/overide/PROJECTS/work/spectra-backend/apps/user/mutation.py", line 5, in <module>
    class UserProfileMutation(BaseSerializerMutation):
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/graphene/utils/subclass_with_meta.py", line 52, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "/home/overide/.local/share/virtualenvs/spectra-backend-WjEFjE6F/lib/python3.7/site-packages/graphene_django/rest_framework/mutation.py", line 97, in __init_subclass_with_meta__
    lookup_field=lookup_field,
TypeError: override_fields() got an unexpected keyword argument 'convert_choices_to_enum'
```
